import { useState, useEffect } from "react";
import { checkSlugExists } from "../../services/blogService";

const SlugInput = ({ value, onChange, title, blogId = null, onSlugChange }) => {
  const [slug, setSlug] = useState(value || "");
  const [isChecking, setIsChecking] = useState(false);
  const [slugExists, setSlugExists] = useState(false);
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);

  useEffect(() => {
    if (title && !slug && !isAutoGenerated) {
      const generated = generateSlug(title);
      setSlug(generated);
      setIsAutoGenerated(true);
      if (onSlugChange) onSlugChange(generated);
    }
  }, [title]);

  useEffect(() => {
    if (slug && slug.length > 0) {
      const timeoutId = setTimeout(async () => {
        setIsChecking(true);
        try {
          const result = await checkSlugExists(slug, blogId);
          setSlugExists(result.exists);
        } catch (error) {
          console.error("Error checking slug:", error);
        } finally {
          setIsChecking(false);
        }
      }, 300);

      return () => clearTimeout(timeoutId);
    } else {
      setSlugExists(false);
    }
  }, [slug, blogId]);

  const generateSlug = (text) => {
    if (!text) return "";
    return text
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .replace(/đ/g, "d")
      .replace(/Đ/g, "D")
      .replace(/[^a-z0-9\s-]/g, "")
      .replace(/\s+/g, "-")
      .replace(/-+/g, "-")
      .trim()
      .substring(0, 500);
  };

  const handleChange = (e) => {
    const newSlug = e.target.value;
    setSlug(newSlug);
    setIsAutoGenerated(false);
    if (onChange) onChange(newSlug);
    if (onSlugChange) onSlugChange(newSlug);
  };

  const handleRegenerate = () => {
    if (title) {
      const generated = generateSlug(title);
      setSlug(generated);
      setIsAutoGenerated(true);
      if (onChange) onChange(generated);
      if (onSlugChange) onSlugChange(generated);
    }
  };

  return (
    <div className="space-y-2">
      <div className="flex items-center justify-between">
        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">
          Slug (URL)
        </label>
        {title && (
          <button
            type="button"
            onClick={handleRegenerate}
            className="text-xs text-blue-600 hover:text-blue-800 dark:text-blue-400"
          >
            Tạo lại từ tiêu đề
          </button>
        )}
      </div>
      <div className="relative">
        <input
          type="text"
          value={slug}
          onChange={handleChange}
          placeholder="slug-url-seo-friendly"
          className={`w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-800 dark:text-white dark:border-gray-600 ${
            slugExists
              ? "border-red-500 focus:ring-red-500"
              : "border-gray-300 focus:ring-blue-500"
          }`}
        />
        {isChecking && (
          <div className="absolute right-3 top-2.5">
            <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-blue-500"></div>
          </div>
        )}
      </div>
      {slugExists && (
        <p className="text-sm text-red-600 dark:text-red-400">
          Slug này đã tồn tại. Vui lòng chọn slug khác.
        </p>
      )}
      {!slugExists && slug && !isChecking && (
        <p className="text-sm text-green-600 dark:text-green-400">
          ✓ Slug có thể sử dụng
        </p>
      )}
    </div>
  );
};

export default SlugInput;
